### PR TITLE
implemented the device contact sensor and basic test.

### PR DESCRIPTION
**Pull request by arlospiki**
The contact sensor implements a non-generic `IBandContactSensor` rather than the generic `IBandSensor<T>` like every other sensor.

### CODE REVIEW

**Comment by arlospiki** [comment]
@peted70 I've resolved the conflicts

**Comment by peted70** [comment]
Hi @rrreynolds,
Firstly, thanks for the contributions much appreciated.

One suggestion I'd like to make about the contact sensor is that ideally the fake sensors should implement and respect the correct update intervals (I didn't have time to implement that yet). It looks like you created a FakeContactSensor class to deal with the differing update frequency? Unless I am misunderstanding the intent it might be better to stick with the FakeBandSensor base class. and have it update with a frequency that makes sense for that sensor (happy to try an implementation of this if my explanation is not clear). Let me know if I missed anything there?

Cheers,
Pete D

**Comment by peted70** [comment]
Having dug a bit deeper I understand why you made that change.

**Comment by arlospiki** [comment]
Glad to hear that Pete. Sorry it wasn't clear initially. I'll try to provide a better description when making changes like that.

**Comment by peted70** [comment]
Would you mind taking a quick look at this alternative implementation here https://github.com/BandOnTheRun/fake-band/pull/10 and let me know if it covers everything? (I noticed some mistakes in my code and a way to avoid some code duplication in your pull request). No worries if you can't check it - just didn't want to make changes to your code without getting your blessing.
Here's what I did:
Changed FakeDeviceContactSensor to inherit IBandContactSensor and FakeBandSensor<IBandContactReading> (this avoids some code repetition).
Fixed Timeout logic in the unit tests.
Fixed FakeBandClient_TestValueReceived_ConnectContactAndReceiveOneValue unit test (this was broken). (Also set the reporting interval of the sensors in the tests to 500ms to avoid waiting for 30s - might need more control over this moving forwards when the sensor supported intervals are implemented). 

Cheers,
Pete D

**Comment by arlospiki** [comment]
#10 looks good to me. Thanks.

**Pull request merged**
